# Generated by Django 5.2.4 on 2025-07-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='responder',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
